[2022-12-10 16:08:52,935] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: mysql-to-gcp.inserting-data-into-bigquery 2022-12-10T15:44:47.638429+00:00 [queued]>
[2022-12-10 16:08:53,743] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: mysql-to-gcp.inserting-data-into-bigquery 2022-12-10T15:44:47.638429+00:00 [queued]>
[2022-12-10 16:08:53,755] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-12-10 16:08:53,764] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-12-10 16:08:53,766] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-12-10 16:08:53,842] {taskinstance.py:1063} INFO - Executing <Task(PythonVirtualenvOperator): inserting-data-into-bigquery> on 2022-12-10T15:44:47.638429+00:00
[2022-12-10 16:08:53,862] {standard_task_runner.py:52} INFO - Started process 104 to run task
[2022-12-10 16:08:53,873] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'mysql-to-gcp', 'inserting-data-into-bigquery', '2022-12-10T15:44:47.638429+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/gcp_dag.py', '--cfg-path', '/tmp/tmpjl7fzrwq', '--error-file', '/tmp/tmpxrdeh91v']
[2022-12-10 16:08:53,887] {standard_task_runner.py:77} INFO - Job 5: Subtask inserting-data-into-bigquery
[2022-12-10 16:08:54,054] {logging_mixin.py:104} INFO - Running <TaskInstance: mysql-to-gcp.inserting-data-into-bigquery 2022-12-10T15:44:47.638429+00:00 [running]> on host ec559b4d8f4f
[2022-12-10 16:08:54,148] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=mysql-to-gcp
AIRFLOW_CTX_TASK_ID=inserting-data-into-bigquery
AIRFLOW_CTX_EXECUTION_DATE=2022-12-10T15:44:47.638429+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-10T15:44:47.638429+00:00
[2022-12-10 16:08:54,152] {process_utils.py:135} INFO - Executing cmd: virtualenv /tmp/venvp1uzejsj --system-site-packages
[2022-12-10 16:08:54,169] {process_utils.py:137} INFO - Output:
[2022-12-10 16:08:55,436] {process_utils.py:141} INFO - created virtual environment CPython3.6.15.final.0-64 in 895ms
[2022-12-10 16:08:55,441] {process_utils.py:141} INFO -   creator CPython3Posix(dest=/tmp/venvp1uzejsj, clear=False, no_vcs_ignore=False, global=True)
[2022-12-10 16:08:55,443] {process_utils.py:141} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/airflow/.local/share/virtualenv)
[2022-12-10 16:08:55,444] {process_utils.py:141} INFO -     added seed packages: pip==21.0.1, setuptools==52.0.0, wheel==0.36.2
[2022-12-10 16:08:55,447] {process_utils.py:141} INFO -   activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
[2022-12-10 16:08:55,514] {process_utils.py:135} INFO - Executing cmd: /tmp/venvp1uzejsj/bin/pip install google-cloud-bigquery google-cloud-bigquery-storage pandas
[2022-12-10 16:08:55,536] {process_utils.py:137} INFO - Output:
[2022-12-10 16:08:58,319] {process_utils.py:141} INFO - Requirement already satisfied: google-cloud-bigquery in /home/airflow/.local/lib/python3.6/site-packages (2.8.0)
[2022-12-10 16:08:58,321] {process_utils.py:141} INFO - Requirement already satisfied: google-cloud-bigquery-storage in /home/airflow/.local/lib/python3.6/site-packages (2.2.1)
[2022-12-10 16:08:58,323] {process_utils.py:141} INFO - Requirement already satisfied: pandas in /home/airflow/.local/lib/python3.6/site-packages (1.1.5)
[2022-12-10 16:08:58,391] {process_utils.py:141} INFO - Requirement already satisfied: protobuf>=3.12.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-cloud-bigquery) (3.14.0)
[2022-12-10 16:08:58,394] {process_utils.py:141} INFO - Requirement already satisfied: google-resumable-media<2.0dev,>=0.6.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-cloud-bigquery) (1.2.0)
[2022-12-10 16:08:58,397] {process_utils.py:141} INFO - Requirement already satisfied: google-cloud-core<2.0dev,>=1.4.1 in /home/airflow/.local/lib/python3.6/site-packages (from google-cloud-bigquery) (1.6.0)
[2022-12-10 16:08:58,399] {process_utils.py:141} INFO - Requirement already satisfied: proto-plus>=1.10.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-cloud-bigquery) (1.13.0)
[2022-12-10 16:08:58,403] {process_utils.py:141} INFO - Requirement already satisfied: google-api-core[grpc]<2.0.0dev,>=1.23.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-cloud-bigquery) (1.26.0)
[2022-12-10 16:08:58,468] {process_utils.py:141} INFO - Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (1.52.0)
[2022-12-10 16:08:58,473] {process_utils.py:141} INFO - Requirement already satisfied: setuptools>=40.3.0 in /tmp/venvp1uzejsj/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (52.0.0)
[2022-12-10 16:08:58,476] {process_utils.py:141} INFO - Requirement already satisfied: six>=1.13.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (1.15.0)
[2022-12-10 16:08:58,480] {process_utils.py:141} INFO - Requirement already satisfied: google-auth<2.0dev,>=1.21.1 in /home/airflow/.local/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (1.26.1)
[2022-12-10 16:08:58,484] {process_utils.py:141} INFO - Requirement already satisfied: packaging>=14.3 in /home/airflow/.local/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (20.9)
[2022-12-10 16:08:58,487] {process_utils.py:141} INFO - Requirement already satisfied: pytz in /home/airflow/.local/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (2020.5)
[2022-12-10 16:08:58,491] {process_utils.py:141} INFO - Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (2.25.1)
[2022-12-10 16:08:58,502] {process_utils.py:141} INFO - Requirement already satisfied: grpcio<2.0dev,>=1.29.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (1.35.0)
[2022-12-10 16:08:58,585] {process_utils.py:141} INFO - Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (4.2.1)
[2022-12-10 16:08:58,589] {process_utils.py:141} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/airflow/.local/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (0.2.8)
[2022-12-10 16:08:58,597] {process_utils.py:141} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/airflow/.local/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (4.7)
[2022-12-10 16:08:58,675] {process_utils.py:141} INFO - Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-resumable-media<2.0dev,>=0.6.0->google-cloud-bigquery) (1.1.2)
[2022-12-10 16:08:58,686] {process_utils.py:141} INFO - Requirement already satisfied: cffi>=1.0.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-crc32c<2.0dev,>=1.0->google-resumable-media<2.0dev,>=0.6.0->google-cloud-bigquery) (1.14.5)
[2022-12-10 16:08:58,693] {process_utils.py:141} INFO - Requirement already satisfied: pycparser in /home/airflow/.local/lib/python3.6/site-packages (from cffi>=1.0.0->google-crc32c<2.0dev,>=1.0->google-resumable-media<2.0dev,>=0.6.0->google-cloud-bigquery) (2.20)
[2022-12-10 16:08:58,727] {process_utils.py:141} INFO - Requirement already satisfied: pyparsing>=2.0.2 in /home/airflow/.local/lib/python3.6/site-packages (from packaging>=14.3->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (2.4.7)
[2022-12-10 16:08:58,755] {process_utils.py:141} INFO - Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/airflow/.local/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (0.4.8)
[2022-12-10 16:08:58,807] {process_utils.py:141} INFO - Requirement already satisfied: chardet<5,>=3.0.2 in /home/airflow/.local/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (3.0.4)
[2022-12-10 16:08:58,810] {process_utils.py:141} INFO - Requirement already satisfied: idna<3,>=2.5 in /home/airflow/.local/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (2.10)
[2022-12-10 16:08:58,812] {process_utils.py:141} INFO - Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/airflow/.local/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (1.25.11)
[2022-12-10 16:08:58,814] {process_utils.py:141} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/airflow/.local/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (2020.12.5)
[2022-12-10 16:08:58,964] {process_utils.py:141} INFO - Requirement already satisfied: libcst>=0.2.5 in /home/airflow/.local/lib/python3.6/site-packages (from google-cloud-bigquery-storage) (0.3.17)
[2022-12-10 16:08:59,059] {process_utils.py:141} INFO - Requirement already satisfied: typing-inspect>=0.4.0 in /home/airflow/.local/lib/python3.6/site-packages (from libcst>=0.2.5->google-cloud-bigquery-storage) (0.6.0)
[2022-12-10 16:08:59,062] {process_utils.py:141} INFO - Requirement already satisfied: typing-extensions>=3.7.4.2 in /home/airflow/.local/lib/python3.6/site-packages (from libcst>=0.2.5->google-cloud-bigquery-storage) (3.7.4.3)
[2022-12-10 16:08:59,064] {process_utils.py:141} INFO - Requirement already satisfied: pyyaml>=5.2 in /home/airflow/.local/lib/python3.6/site-packages (from libcst>=0.2.5->google-cloud-bigquery-storage) (5.4.1)
[2022-12-10 16:08:59,068] {process_utils.py:141} INFO - Requirement already satisfied: dataclasses>=0.6.0 in /home/airflow/.local/lib/python3.6/site-packages (from libcst>=0.2.5->google-cloud-bigquery-storage) (0.7)
[2022-12-10 16:08:59,134] {process_utils.py:141} INFO - Requirement already satisfied: mypy-extensions>=0.3.0 in /home/airflow/.local/lib/python3.6/site-packages (from typing-inspect>=0.4.0->libcst>=0.2.5->google-cloud-bigquery-storage) (0.4.3)
[2022-12-10 16:08:59,189] {process_utils.py:141} INFO - Requirement already satisfied: python-dateutil>=2.7.3 in /home/airflow/.local/lib/python3.6/site-packages (from pandas) (2.8.1)
[2022-12-10 16:08:59,194] {process_utils.py:141} INFO - Requirement already satisfied: numpy>=1.15.4 in /home/airflow/.local/lib/python3.6/site-packages (from pandas) (1.19.5)
[2022-12-10 16:09:16,632] {process_utils.py:141} INFO - WARNING: You are using pip version 21.0.1; however, version 21.3.1 is available.
[2022-12-10 16:09:16,633] {process_utils.py:141} INFO - You should consider upgrading via the '/tmp/venvp1uzejsj/bin/python -m pip install --upgrade pip' command.
[2022-12-10 16:09:16,846] {process_utils.py:135} INFO - Executing cmd: /tmp/venvp1uzejsj/bin/python /tmp/venvp1uzejsj/script.py /tmp/venvp1uzejsj/script.in /tmp/venvp1uzejsj/script.out /tmp/venvp1uzejsj/string_args.txt
[2022-12-10 16:09:16,856] {process_utils.py:137} INFO - Output:
[2022-12-10 16:09:25,685] {process_utils.py:141} INFO - Traceback (most recent call last):
[2022-12-10 16:09:25,688] {process_utils.py:141} INFO -   File "/tmp/venvp1uzejsj/script.py", line 82, in <module>
[2022-12-10 16:09:25,689] {process_utils.py:141} INFO -     res = insert(*arg_dict["args"], **arg_dict["kwargs"])
[2022-12-10 16:09:25,690] {process_utils.py:141} INFO -   File "/tmp/venvp1uzejsj/script.py", line 39, in insert
[2022-12-10 16:09:25,691] {process_utils.py:141} INFO -     connection = mysql_hook.get_conn()
[2022-12-10 16:09:25,693] {process_utils.py:141} INFO -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/hooks/mysql.py", line 136, in get_conn
[2022-12-10 16:09:25,695] {process_utils.py:141} INFO -     conn = self.connection or self.get_connection(self.mysql_conn_id)  # pylint: disable=no-member
[2022-12-10 16:09:25,696] {process_utils.py:141} INFO -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 63, in get_connection
[2022-12-10 16:09:25,698] {process_utils.py:141} INFO -     conn = Connection.get_connection_from_secrets(conn_id)
[2022-12-10 16:09:25,699] {process_utils.py:141} INFO -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 354, in get_connection_from_secrets
[2022-12-10 16:09:25,700] {process_utils.py:141} INFO -     raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
[2022-12-10 16:09:25,702] {process_utils.py:141} INFO - airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_default` isn't defined
[2022-12-10 16:09:26,348] {taskinstance.py:1455} ERROR - Command '['/tmp/venvp1uzejsj/bin/python', '/tmp/venvp1uzejsj/script.py', '/tmp/venvp1uzejsj/script.in', '/tmp/venvp1uzejsj/script.out', '/tmp/venvp1uzejsj/string_args.txt']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 493, in execute
    super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 531, in execute_callable
    string_args_filename,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/process_utils.py", line 145, in execute_in_subprocess
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venvp1uzejsj/bin/python', '/tmp/venvp1uzejsj/script.py', '/tmp/venvp1uzejsj/script.in', '/tmp/venvp1uzejsj/script.out', '/tmp/venvp1uzejsj/string_args.txt']' returned non-zero exit status 1.
[2022-12-10 16:09:26,355] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=mysql-to-gcp, task_id=inserting-data-into-bigquery, execution_date=20221210T154447, start_date=20221210T160852, end_date=20221210T160926
[2022-12-10 16:09:26,416] {local_task_job.py:146} INFO - Task exited with return code 1
